
#spring.datasource.url=jdbc:postgresql://ep-mute-lake-ahjzl7r8-pooler.c-3.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
#spring.datasource.username=neondb_owner
#spring.datasource.password=npg_f65olyGbQiuD


spring.datasource.url=jdbc:postgresql://localhost:5432/school
spring.datasource.username=postgres
spring.datasource.password=123




spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

logging.level.root=INFO
spring.mvc.servlet.load-on-startup=1
spring.web.resources.static-locations=classpath:/static/

# ---------------------------------------
#   Hibernate / JPA Configuration
# ---------------------------------------
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

